"""add emergency contacts

Revision ID: 694ced8dc659
Revises: 00777d532fc5
Create Date: 2026-04-30 16:19:39.425139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '694ced8dc659'
down_revision: Union[str, Sequence[str], None] = '00777d532fc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_contact',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=255), nullable=False),
    sa.Column('relation', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_contact_email'), 'emergency_contact', ['email'], unique=False)
    op.create_index(op.f('ix_emergency_contact_id'), 'emergency_contact', ['id'], unique=False)
    op.create_index(op.f('ix_emergency_contact_phone_number'), 'emergency_contact', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emergency_contact_phone_number'), table_name='emergency_contact')
    op.drop_index(op.f('ix_emergency_contact_id'), table_name='emergency_contact')
    op.drop_index(op.f('ix_emergency_contact_email'), table_name='emergency_contact')
    op.drop_table('emergency_contact')
    # ### end Alembic commands ###
