"""Refactor User schema and add Account model

Revision ID: 00777d532fc5
Revises: c89c7e95174e
Create Date: 2026-04-22 16:11:46.759602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00777d532fc5'
down_revision: Union[str, Sequence[str], None] = 'c89c7e95174e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('billing_status', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_billing_status'), 'accounts', ['billing_status'], unique=False)
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.add_column('users', sa.Column('first_name', sa.String(length=255), server_default='Unknown', nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=255), server_default='Unknown', nullable=False))
    op.add_column('users', sa.Column('role', sa.String(length=255), server_default='Unknown', nullable=False))
    op.add_column('users', sa.Column('account_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('users_invited_by_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'accounts', ['account_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'users', 'users', ['invited_by'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_invited_by_fkey'), 'users', 'users', ['invited_by'], ['id'])
    op.drop_column('users', 'account_id')
    op.drop_column('users', 'role')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_billing_status'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
