"""add_care_assignments_table

Revision ID: a5d515ddaf44
Revises: 3bb0ea9a4565
Create Date: 2026-06-16 17:29:25.183209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5d515ddaf44'
down_revision: Union[str, Sequence[str], None] = '3bb0ea9a4565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('caregiver_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('caregiver_id', 'patient_id', name='uq_caregiver_patient')
    )
    op.create_index(op.f('ix_care_assignments_caregiver_id'), 'care_assignments', ['caregiver_id'], unique=False)
    op.create_index(op.f('ix_care_assignments_id'), 'care_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_care_assignments_patient_id'), 'care_assignments', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_care_assignments_patient_id'), table_name='care_assignments')
    op.drop_index(op.f('ix_care_assignments_id'), table_name='care_assignments')
    op.drop_index(op.f('ix_care_assignments_caregiver_id'), table_name='care_assignments')
    op.drop_table('care_assignments')
    # ### end Alembic commands ###
