"""add journal table

Revision ID: 3b777f5a6dd9
Revises: b646987d2817
Create Date: 2026-05-07 16:22:42.644277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b777f5a6dd9'
down_revision: Union[str, Sequence[str], None] = 'b646987d2817'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('journals', 'user_diary_entry',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('journals', 'author_diary_entry',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('journals', 'author_diary_entry',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('journals', 'user_diary_entry',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
